#!/bin/sh
#
# binder servicemanager
#

PID_FILE=/tmp/binder_svr.pid

DAEMON=servicemanager
DAEMON_ARGS=""

start() {
  if [ -f $PID_FILE ] && kill -0 $(cat $PID_FILE); then
    echo "$DAEMON already running"
    return 1
  fi
  printf "Starting $DAEMON..."
  eval "$DAEMON $DAEMON_ARGS &"
  echo $! > $PID_FILE
}

stop() {
  if [ ! -f "$PID_FILE" ] || ! kill -0 $(cat "$PID_FILE"); then
    echo "$DAEMON not running"
    return 1
  fi
  printf "Stopping $DAEMON "
  kill $(cat $PID_FILE) && rm -f $PID_FILE
  echo "$DAEMON stopped"
}

restart() {
  stop
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
