LIBBINDER_PROJDIR  := $(AML_COMMON_DIR)/aml_commonlib/libbinder
LIBBINDER_OSS_LIC  := CLOSED
LIBBINDER_DEPENDS  := linux_kernel
LIBBINDER_BINARIES := usr/lib/libbinder.so usr/bin/servicemanager
LIBBINDER_ADD_SRC  := $(ROKU_OS_INCLUDE_DIRS)

$(eval $(call prep_proj,LIBBINDER,libbinder,$(LIBBINDER_PROJDIR),$(LIBBINDER_ADD_SRC)))

LDFLAGS = $(addprefix -L, $(ROKU_3PARTY_LIB_DIRS))
LIBBINDER_MAKE_OPTIONS = \
	CC=$(CC) \
	CXX=$(CXX) \
	OUT_ROOT=$(LIBBINDER_MAKEDIR) \
	PORTING_KIT_OS=$(PORTING_KIT_OS) \
	LDFLAGS="$(LDFLAGS)" \
	PLATFORMDIR=$(PLATFORMDIR) \
	AML_COMMON_DIR=$(AML_COMMON_DIR) \
	ROKU_PORT_COMMON_DIR=$(ROKU_PORT_COMMON_DIR) \
	ROKU_PORT_DIR=$(ROKU_PORT_DIR) \
	ROKU_3PARTY_INCLUDE_DIRS=$(ROKU_3PARTY_INCLUDE_DIRS) \
	ROKU_STAGING_DIR=$(ROKU_STAGING_DIR) \
	CROSSTOOLS_SYSROOT_PATH=$(CROSSTOOLS_SYSROOT_PATH)

libbinder-build:
	(PATH=$(CROSSTOOLS_BIN):$(PATH) \
	$(MAKE) -f Makefile.roku -C $(LIBBINDER_PROJDIR) $(LIBBINDER_MAKE_OPTIONS) all)

libbinder-install:
	$(MAKE) -f Makefile.roku -C $(LIBBINDER_PROJDIR) DESTDIR=$(LIBBINDER_INSTDIR) $(LIBBINDER_MAKE_OPTIONS) DESTDIR=$(ROKU_STAGING_DIR)/$(LIBBINDER_DESTDIR) install

libbinder-clean:
	$(MAKE) -f Makefile.roku -C $(LIBBINDER_PROJDIR) $(LIBBINDER_INSTDIR) clean || true

libbinder-distclean:
	$(MAKE) -f Makefile.roku -C $(LIBBINDER_PROJDIR) $(LIBBINDER_MAKE_OPTIONS) DESTDIR=$(ROKU_STAGING_DIR)/$(LIBBINDER_DESTDIR) distclean || true
